server:
  port: 8189
spring:
  profiles:
    active: local
  application:
    name: ddd-layout-template
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: info
# springdoc-openapi config
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'ddd-layout-template'
      paths-to-match: '/api/**'
      packages-to-scan: com.ryan.ddd.adapter
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn

# OpenTelemetry config
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
