spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.ryan.ddd.infra.common.persistence

outbox:
  publisher:
    fixedDelayMs: 2000

messaging:
  # SPRING or KAFKA
  mode: KAFKA
  kafka:
    topic: ddd-events
    consumer-group-id: ddd-layout-template
